# this workflow will run nodejs coverages and tests
# and upload build-artifacts to branch-gh-pages
name: ci
on:
  push:
    branches:
      # - '*/*/*'
      - alpha
      - beta
      - master
      - sandbox
  workflow_dispatch:
env:
  CI_MAIN_JOB: node.v18.x64.linux
  GITHUB_ARTIFACT_UPLOAD_NODE_VERSION: v18
  # MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
jobs:


# shCiBase - start
  job1:
    strategy:
      matrix:
        architecture:
          # - arm64
          - x64
          # - x86
        node_version:
          - 16
          - 18
          - 19
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    name: >
      job1
      node
      v${{ matrix.node_version }}
      ${{ matrix.architecture }}
      ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      # disable autocrlf in windows
      - run: git config --global core.autocrlf false
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
      # fetch jslint_ci.sh from trusted source
      - run: |
          git fetch origin alpha
          git checkout origin/alpha .ci.sh jslint_ci.sh
      # pre-run .ci.sh
      - run: sh jslint_ci.sh shCiPre
      # https://github.com/actions/cache
      - uses: actions/cache@v3
        with:
          key: >
            ${{ hashFiles('./package.json') }}
            ${{ matrix.architecture }}
            ${{ matrix.node_version }}
            ${{ matrix.os }}
          path: .github_cache
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      # run nodejs coverages and tests
      - run: sh jslint_ci.sh shCiBase
# shCiBase - end


# shCiArtifactUpload - start
      # fetch jslint_ci.sh from trusted source
      - run: |
          git fetch origin alpha
          git checkout origin/alpha .ci.sh jslint_ci.sh
      # upload build-artifacts to branch-gh-pages
      - run: sh jslint_ci.sh shCiArtifactUpload
# shCiArtifactUpload - end
