# this workflow will run nodejs coverages and tests
# and upload build-artifacts to branch-gh-pages
name: ci
on:
  push:
    branches:
      - alpha
      - beta
      - master
      - sandbox
  workflow_dispatch:
    branches:
      - alpha
      - beta
      - master
      - sandbox
jobs:
# shCiBase - start
  job1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        architecture:
          # - arm64
          - x64
          # - x86
        node_version:
          # - 12
          - 14
          # - 16
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    name: job1 . node . v${{ matrix.node_version }} . ${{ matrix.architecture }} . ${{ matrix.os }}
    steps:
      # disable autocrlf in windows
      - run: git config --global core.autocrlf false
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      # fetch jslint_ci.sh from trusted source
      - run: git fetch origin alpha && git checkout origin/alpha jslint_ci.sh
      # run nodejs coverages and tests
      - run: sh jslint_ci.sh shCiBase
# shCiBase - end
# shCiArtifactUpload - start
      # fetch jslint_ci.sh from trusted source
      - run: git fetch origin alpha && git checkout origin/alpha jslint_ci.sh
      # upload build-artifacts to branch-gh-pages
      - run: sh jslint_ci.sh shCiArtifactUpload
        env:
          CI_NODE_VERSION_ARCH_PLATFORM: v14.x64.linux
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# shCiArtifactUpload - end
# upload binaries - start
      - uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: .binary-*
# upload binaries - end
  job2:
    needs: job1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        architecture:
          - x64
        node_version:
          # - 12
          - 14
          # - 16
        os:
          - ubuntu-latest
    name: job2 . node . v${{ matrix.node_version }} . ${{ matrix.architecture }} . ${{ matrix.os }}
    steps:
      # disable autocrlf in windows
      - run: git config --global core.autocrlf false
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
# download binaries - start
      - uses: actions/download-artifact@v2
        with:
          name: binaries
# download binaries - end
# shCiArtifactUpload2 - start
      # fetch jslint_ci.sh from trusted source
      - run: git fetch origin alpha && git checkout origin/alpha jslint_ci.sh
      # upload build-artifacts to branch-gh-pages
      - run: sh jslint_ci.sh shCiArtifactUpload2
        env:
          CI_NODE_VERSION_ARCH_PLATFORM: v14.x64.linux
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# shCiArtifactUpload2 - end
